# -*- coding: utf-8 -*-
"""Vectors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oo4cJPHPaCWLfSGZNzUOji-zra43CjzQ
"""

import math
from scipy.spatial import distance
__dix=[""]
def loadDB(dbloc):
  db=open(dbloc).readlines()
  for i in db:
    __dix.append(list((i.split())))
  for j in range(1,len(__dix)):
    __dix[j]=[float(x) for x in __dix[j]]
  return len(db)

def add(v):
  __dix[0]=list(v)
def pop():
  __dix[0]=" "
def tam():
  return len(__dix)
def printObj(x,r):
  print(f"{x}---->{r}")

def Distance(i,j):
  distan=distance.euclidean(__dix[i],__dix[j])  
  return distan